theme: jekyll-theme-minimal
title: [Introvision]
description: [Introduction to Computer Vision]
logo: [https://github.com/dani-lbnl/introvision/blob/main/cameracomputervision.png]
show_downloads: ["true"]
